// The ten levels of the third game, in the order the Defector walks them: out
// of the grid's last room and into the world, each place less drawn and more
// real than the one before (the renderer's `real`), its machines less like
// polyhedra and more like things someone built, and its music less like the
// grid's and more like people playing (`humanity`, for the audio). Each is a
// list of sections (sections.js) with a theme, a roster and scenery.
// DOM-free.
import { Builder } from './build.js';
import { rng } from './math.js';
import { SECTIONS } from './sections.js';
import { SECRETS } from './secrets.js';
import { WORKSHOP_LINES } from './story.js';

/**
 * The look of a level: its sky ([overhead, horizon, below]), fog, sun, the
 * grid's edge colour, and what each part of a level (a role) is made of.
 */
const THEMES = {
  // Echo, the bonus level: the grid as it remembers you, in red.
  echo: {
    real: 0,
    sky: ['#0a0104', '#420c1c', '#000000'],
    fog: '#1c0408',
    fogDen: 0.013,
    sun: [0.2, 0.2, 1],
    sunCol: '#ff4f6a',
    sunDisc: '#ff9a3a',
    sunAmt: 0.35,
    sunSize: 70,
    amb: 0.5,
    edge: '#ff3a6a',
    stars: 1,
    gridSky: 1,
    roles: {
      floor: { mat: 'grid', color: '#ff3a6a' },
      arena: { mat: 'grid', color: '#ff9a3a' },
      wall: { mat: 'panel', color: '#ff9a3a' },
      arenaWall: { mat: 'panel', color: '#c2185b' },
      roof: { mat: 'panel', color: '#c2185b' },
      plat: { mat: 'panel', color: '#ffd36a' },
      trim: { mat: 'panel', color: '#c2185b' },
      door: { mat: 'panel', color: '#ffd36a', glow: 0.25 },
      ramp: { mat: 'panel', color: '#ff9a3a' },
      spring: { mat: 'lamp', color: '#ffd36a' },
      crusher: { mat: 'panel', color: '#ff5c7a' },
      blink: { mat: 'panel', color: '#ff9ac8' },
      cover: { mat: 'cracked', color: '#ff3a6a' },
      crate0: { mat: 'crate', color: '#ffd36a' },
    },
  },
  edge: {
    real: 0,
    sky: ['#02010a', '#1c0c42', '#000000'],
    fog: '#070420',
    fogDen: 0.012,
    sun: [0.1, 0.18, 1],
    sunCol: '#b04fff',
    sunDisc: '#ff4fd8',
    sunAmt: 0.35,
    sunSize: 60,
    amb: 0.5,
    edge: '#7fe9ff',
    stars: 1,
    gridSky: 1,
    roles: {
      floor: { mat: 'grid', color: '#27d9ff' },
      arena: { mat: 'grid', color: '#ff4fd8' },
      wall: { mat: 'panel', color: '#ff4fd8' },
      arenaWall: { mat: 'panel', color: '#7f5cff' },
      roof: { mat: 'panel', color: '#7f5cff' },
      plat: { mat: 'panel', color: '#ffb347' },
      trim: { mat: 'panel', color: '#7f5cff' },
      door: { mat: 'panel', color: '#ffb347', glow: 0.25 },
      ramp: { mat: 'panel', color: '#9dff5c' },
      spring: { mat: 'lamp', color: '#9dff5c' },
      crusher: { mat: 'panel', color: '#ff5c7a' },
      blink: { mat: 'panel', color: '#c9a2ff' },
      cover: { mat: 'cracked', color: '#27d9ff' },
      crate0: { mat: 'crate', color: '#ffb347' },
    },
  },
  wilds: {
    real: 0.1,
    sky: ['#010a10', '#0c3340', '#010608'],
    fog: '#04151a',
    fogDen: 0.013,
    sun: [-0.3, 0.3, 1],
    sunCol: '#5affc8',
    sunDisc: '#bfffe8',
    sunAmt: 0.45,
    sunSize: 30,
    amb: 0.55,
    edge: '#5affc8',
    stars: 0.7,
    gridSky: 0.6,
    roles: {
      floor: { mat: 'grid', color: '#3dff9a' },
      arena: { mat: 'grid', color: '#3dff9a' },
      wall: { mat: 'wire', color: '#2de0ff' },
      arenaWall: { mat: 'wire', color: '#2de0ff' },
      roof: { mat: 'wire', color: '#2de0ff' },
      plat: { mat: 'panel', color: '#b8ff6a' },
      trim: { mat: 'panel', color: '#2de0ff' },
      door: { mat: 'panel', color: '#ffe066', glow: 0.25 },
      ramp: { mat: 'panel', color: '#ffe066' },
      spring: { mat: 'lamp', color: '#b8ff6a' },
      blink: { mat: 'panel', color: '#c9a2ff' },
      cover: { mat: 'cracked', color: '#3dff9a' },
      crate0: { mat: 'crate', color: '#b8ff6a' },
    },
  },
  farm: {
    real: 0.22,
    sky: ['#05080d', '#0d1622', '#05070a'],
    fog: '#081018',
    fogDen: 0.022,
    sun: [0.3, 0.9, 0.2],
    sunCol: '#8ab8ff',
    sunAmt: 0.5,
    amb: 0.55,
    edge: '#4fb8ff',
    roles: {
      floor: { mat: 'metal', color: '#5a6678' },
      arena: { mat: 'metal', color: '#5a6678' },
      wall: { mat: 'metal', color: '#3a4556' },
      arenaWall: { mat: 'metal', color: '#3a4556' },
      roof: { mat: 'metal', color: '#2a3140' },
      plat: { mat: 'metal', color: '#7a8a9e' },
      trim: { mat: 'metal', color: '#4fb8ff' },
      door: { mat: 'hazard', color: '#ffb347' },
      ramp: { mat: 'metal', color: '#9dc8ff' },
      spring: { mat: 'lamp', color: '#4fb8ff' },
      crusher: { mat: 'hazard', color: '#ffb347' },
      blink: { mat: 'panel', color: '#4fb8ff' },
      cover: { mat: 'cracked', color: '#3a4556' },
      crate0: { mat: 'crate', color: '#7a8a9e' },
    },
  },
  foundry: {
    real: 0.36,
    sky: ['#120806', '#3a1a0c', '#0a0503'],
    fog: '#22110a',
    fogDen: 0.018,
    sun: [0.4, 0.8, -0.3],
    sunCol: '#ffb070',
    sunAmt: 0.7,
    amb: 0.6,
    edge: '#ff9a4a',
    roles: {
      floor: { mat: 'concrete', color: '#7a7068' },
      arena: { mat: 'concrete', color: '#7a7068' },
      wall: { mat: 'brick', color: '#6a3a2a' },
      arenaWall: { mat: 'brick', color: '#5a3226' },
      roof: { mat: 'metal', color: '#3a3430' },
      plat: { mat: 'metal', color: '#8a7a66' },
      trim: { mat: 'metal', color: '#4a4440' },
      door: { mat: 'hazard', color: '#ffb347' },
      ramp: { mat: 'hazard', color: '#ffb347' },
      spring: { mat: 'metal', color: '#c8b070' },
      crusher: { mat: 'metal', color: '#6a6a70' },
      blink: { mat: 'metal', color: '#ff9a4a', glow: 0.2 },
      cover: { mat: 'cracked', color: '#6a3a2a' },
      crate0: { mat: 'crate', color: '#9a7a52' },
    },
  },
  freeway: {
    real: 0.48,
    sky: ['#03060f', '#1e2a4a', '#07080c'],
    fog: '#0e1424',
    fogDen: 0.008,
    sun: [-0.4, 0.5, 0.3],
    sunCol: '#9ab0e0',
    sunDisc: '#f2f0e6',
    sunSize: 3,
    sunAmt: 0.75,
    amb: 0.9,
    edge: '#ffb35a',
    stars: 0.4,
    roles: {
      floor: { mat: 'asphalt', color: '#6a6c72' },
      arena: { mat: 'asphalt', color: '#6a6c72' },
      wall: { mat: 'concrete', color: '#9a9a94' },
      arenaWall: { mat: 'concrete', color: '#8a8a84' },
      roof: { mat: 'concrete', color: '#6a6a66' },
      plat: { mat: 'concrete', color: '#a8a8a0' },
      trim: { mat: 'metal', color: '#6a7078' },
      door: { mat: 'hazard', color: '#ffb347' },
      ramp: { mat: 'hazard', color: '#ffb347' },
      spring: { mat: 'metal', color: '#c83a2a' },
      crusher: { mat: 'metal', color: '#7a7a80' },
      blink: { mat: 'lamp', color: '#ffb35a' },
      cover: { mat: 'cracked', color: '#9a9a94' },
      crate0: { mat: 'container', color: '#3a6a9a' },
    },
  },
  rain: {
    real: 0.58,
    sky: ['#0a0e1c', '#2a3450', '#0a0a12'],
    fog: '#1a2234',
    fogDen: 0.016,
    sun: [0.3, 0.6, 0.4],
    sunCol: '#8a9ac8',
    sunAmt: 0.4,
    amb: 0.6,
    edge: '#ff4fd8',
    rain: 1,
    roles: {
      floor: { mat: 'concrete', color: '#56585e' },
      arena: { mat: 'concrete', color: '#56585e' },
      wall: { mat: 'brick', color: '#7a4232' },
      arenaWall: { mat: 'brick', color: '#6a3a2e' },
      roof: { mat: 'concrete', color: '#4a4a4e' },
      plat: { mat: 'metal', color: '#6a7078' },
      trim: { mat: 'metal', color: '#3a3e44' },
      door: { mat: 'metal', color: '#8a8a90' },
      ramp: { mat: 'metal', color: '#9aa0a8' },
      spring: { mat: 'metal', color: '#c8b070' },
      crusher: { mat: 'metal', color: '#6a6a70' },
      blink: { mat: 'lamp', color: '#ff4fd8' },
      cover: { mat: 'cracked', color: '#7a4232' },
      crate0: { mat: 'crate', color: '#8a6a44' },
    },
  },
  underline: {
    real: 0.68,
    sky: ['#0a0908', '#1a1612', '#050404'],
    fog: '#14110c',
    fogDen: 0.022,
    sun: [0.2, 1, 0.1],
    sunCol: '#ffe0b0',
    sunAmt: 0.55,
    amb: 0.55,
    edge: '#ffd08a',
    roles: {
      floor: { mat: 'tile', color: '#9a9482' },
      arena: { mat: 'tile', color: '#8a8472' },
      wall: { mat: 'tile', color: '#d8d0b0' },
      arenaWall: { mat: 'concrete', color: '#8a8478' },
      roof: { mat: 'concrete', color: '#5a5650' },
      plat: { mat: 'concrete', color: '#9a968c' },
      trim: { mat: 'metal', color: '#4a4640' },
      door: { mat: 'metal', color: '#8a3a2a' },
      ramp: { mat: 'metal', color: '#c8a050' },
      spring: { mat: 'metal', color: '#c8a050' },
      crusher: { mat: 'metal', color: '#5a5a60' },
      blink: { mat: 'lamp', color: '#ffd08a' },
      cover: { mat: 'cracked', color: '#d8d0b0' },
      crate0: { mat: 'crate', color: '#8a6a44' },
    },
  },
  harbour: {
    real: 0.8,
    sky: ['#3a5a8a', '#f4b890', '#3a4a58'],
    fog: '#c8a898',
    fogDen: 0.009,
    sun: [0.1, 0.12, 1],
    sunCol: '#ffd0a0',
    sunDisc: '#fff0d8',
    sunSize: 4,
    sunAmt: 1.2,
    amb: 0.65,
    edge: '#ffd0a0',
    clouds: 0.6,
    roles: {
      floor: { mat: 'concrete', color: '#9a9890' },
      arena: { mat: 'concrete', color: '#9a9890' },
      wall: { mat: 'container', color: '#b8432e' },
      arenaWall: { mat: 'container', color: '#2e6ab8' },
      roof: { mat: 'metal', color: '#6a6a6a' },
      plat: { mat: 'wood', color: '#8a6a44' },
      trim: { mat: 'metal', color: '#d8a030' },
      door: { mat: 'container', color: '#2e8a4a' },
      ramp: { mat: 'metal', color: '#d8a030' },
      spring: { mat: 'metal', color: '#d8a030' },
      crusher: { mat: 'metal', color: '#6a6a70' },
      blink: { mat: 'wood', color: '#a8844e' },
      cover: { mat: 'cracked', color: '#9a9890' },
      crate0: { mat: 'container', color: '#b8432e' },
    },
  },
  ridge: {
    real: 0.9,
    sky: ['#4a86d0', '#dceaf6', '#5a6a5a'],
    fog: '#d4e2ee',
    fogDen: 0.009,
    sun: [0.5, 0.55, 0.4],
    sunCol: '#fff4e0',
    sunDisc: '#ffffff',
    sunSize: 3,
    sunAmt: 1.35,
    amb: 0.6,
    edge: '#dff6ff',
    clouds: 0.7,
    roles: {
      floor: { mat: 'snow', color: '#eef2f6' },
      arena: { mat: 'snow', color: '#eef2f6' },
      wall: { mat: 'rock', color: '#8a8a88' },
      arenaWall: { mat: 'rock', color: '#7a7a78' },
      roof: { mat: 'rock', color: '#6a6a68' },
      plat: { mat: 'wood', color: '#8a6a48' },
      trim: { mat: 'wood', color: '#6a4a30' },
      door: { mat: 'wood', color: '#7a4a2a' },
      ramp: { mat: 'rock', color: '#9a9a96' },
      spring: { mat: 'wood', color: '#a8844e' },
      crusher: { mat: 'rock', color: '#6a6a68' },
      blink: { mat: 'glass', color: '#bfefff' },
      cover: { mat: 'cracked', color: '#8a8a88' },
      crate0: { mat: 'crate', color: '#8a6a44' },
      rock: { mat: 'rock', color: '#8a8a88' },
    },
  },
  workshop: {
    real: 1,
    sky: ['#1a1410', '#3a2a1c', '#100c08'],
    fog: '#2a1c12',
    fogDen: 0.012,
    sun: [0.3, 0.8, 0.5],
    sunCol: '#ffe0b0',
    sunAmt: 1,
    amb: 1,
    edge: '#ffd08a',
    roles: {
      floor: { mat: 'wood', color: '#8a5a36' },
      arena: { mat: 'wood', color: '#7a4e30' },
      wall: { mat: 'brick', color: '#8a5a44' },
      arenaWall: { mat: 'brick', color: '#7a4a3a' },
      roof: { mat: 'wood', color: '#5a3a22' },
      plat: { mat: 'wood', color: '#a07a4e' },
      trim: { mat: 'metal', color: '#b8903a' },
      door: { mat: 'wood', color: '#6a3a1e' },
      ramp: { mat: 'wood', color: '#b8903a' },
      spring: { mat: 'metal', color: '#b8903a' },
      crusher: { mat: 'metal', color: '#8a7a5a' },
      blink: { mat: 'paper', color: '#f2ecdc' },
      cover: { mat: 'cracked', color: '#8a5a44' },
      crate0: { mat: 'crate', color: '#8a6a44' },
      shelf: { mat: 'wood', color: '#6b4a2e' },
    },
  },
};

// Roles every theme shares, unless it says otherwise.
const COMMON_ROLES = {
  glass: { mat: 'glass', color: '#9fe8ff' },
  switch: { mat: 'lamp', color: '#ffb347' },
  pad: { mat: 'lamp', color: '#9dff5c' },
  rock: { mat: 'rock', color: '#8a8a88' },
  shelf: { mat: 'wood', color: '#6b4a2e' },
};

/**
 * The levels. `real` (in the theme) and `humanity` run from 0 to 1 across
 * the game. A roster is the level's machines: each a way of moving (enemies.js)
 * and a look (art.js).
 */
export const LEVEL_DEFS = [
  {
    id: 1,
    key: 'edge',
    title: 'Edge of the Grid',
    boss: 'warden',
    humanity: 0,
    seed: 101,
    width: 8,
    accent: '#7fe9ff',
    tier: 'early',
    brief: 'The last room of the grid has no fourth wall. Beyond it, for the first time, there is depth.',
    record: 'LOG: A program has passed the last wall. It is looking at something the grid never rendered: distance.',
    roster: [
      { move: 'flier', look: 'glyph', color: '#ff4fd8' },
      { move: 'walker', look: 'cubelet', color: '#ffb347' },
      { move: 'zigzag', look: 'spark', color: '#7fe9ff' },
      { move: 'turret', look: 'prism', color: '#ff5c7a' },
    ],
    decor: [{ kind: 'monolith', color: '#7f5cff', off: 6, spread: 14 }, { kind: 'wiretree', color: '#27d9ff', color2: '#ff4fd8', off: 3, spread: 8 }],
    far: [{ kind: 'mountain', color: '#7f5cff', n: 10 }],
    sections: [
      ['start', { len: 16 }],
      ['run', { len: 14, foes: 0 }],
      ['gap', { gap: 2.6 }],
      ['climb', { steps: 2 }],
      ['run', { len: 16, foes: 1 }],
      ['glitch'],
      ['stones', { n: 3, flat: true }],
      ['checkpoint'],
      ['switchdoor'],
      ['gap', { gap: 5, run: true }],
      ['turn', { dir: 1 }],
      ['run', { len: 14, foes: 2 }],
      ['cache'],
      ['secret', { prize: 'triple' }],
      ['bulkhead', { gapH: 1.3, thick: 2 }],
      ['checkpoint'],
      ['mover', { gap: 12 }],
      ['run', { len: 12, foes: 1 }],
      ['hideaway', { puzzle: 'slit', prize: 'big' }],
      ['crawl'],
      ['tower', { h: 10 }],
      ['gap', { gap: 3.2, rise: -1 }],
      ['turn', { dir: -1 }],
      ['stones', { n: 4 }],
      ['checkpoint'],
      ['run', { len: 10, foes: 2 }],
      ['arena', { boss: 'warden' }],
    ],
    signs: {
      0: 'Look with the mouse (click to capture it). Move with W A S D, and hold Shift to run.',
      1: 'Space jumps: hold it for higher.',
      4: 'Click to fire the blaster. A charge turns off walls at the speed it arrived.',
      8: 'An amber switch opens its door: shoot it.',
      12: 'Listen when you shoot. A panel with room behind it knocks hollow, and near one there is a hum.',
      13: 'That panel is cracked. A few charges break it.',
      14: 'Too low to crawl under. Right click (or Q) opens the light end of a wormhole where you look, E the dark one. One through the slot, onto the floor beyond; one at your feet.',
      16: 'A platform to ride. Stand on it and it carries you.',
    },
  },
  {
    id: 2,
    key: 'wilds',
    title: 'Wireframe Wilds',
    boss: 'stag',
    humanity: 0.1,
    seed: 202,
    width: 8,
    accent: '#3dff9a',
    tier: 'early',
    brief: 'A forest the grid was taught to draw from pictures: every tree a wire, every river a stream of numbers.',
    record: 'LOG: The program is in the training wood. The wood was made to teach the grid what a forest is. It never learned.',
    roster: [
      { move: 'chaser', look: 'wirehound', color: '#3dff9a' },
      { move: 'diver', look: 'wirebird', color: '#2de0ff' },
      { move: 'hopper', look: 'wiretoad', color: '#b8ff6a' },
      { move: 'zigzag', look: 'glyph', color: '#ffe066' },
    ],
    decor: [{ kind: 'wiretree', color: '#3dff9a', color2: '#2de0ff', off: 2, spread: 10 }, { kind: 'wiretree', color: '#2de0ff', color2: '#b8ff6a', off: 5, spread: 14 }],
    far: [{ kind: 'mountain', color: '#2de0ff', n: 12 }],
    sections: [
      ['start', { len: 14 }],
      ['run', { len: 16, foes: 1 }],
      ['lookback'],
      ['stones', { n: 4 }],
      ['turn', { dir: -1 }],
      ['gap', { gap: 5.5, run: true }],
      ['run', { len: 14, foes: 2 }],
      ['targets'],
      ['checkpoint'],
      ['chasm', { gap: 12 }],
      ['climb', { steps: 3 }],
      ['switchdoor', { timed: 7 }],
      ['mover', { gap: 14 }],
      ['turn', { dir: 1 }],
      ['loft', { prize: 'shield' }],
      ['checkpoint'],
      ['run', { len: 14, foes: 2 }],
      ['hideaway', { puzzle: 'slit', prize: 'triple' }],
      ['glitch'],
      ['stones', { n: 5, hard: true }],
      ['bulkhead', { gapH: 1.2, thick: 3 }],
      ['gap', { gap: 5, run: true, rise: 1 }],
      ['checkpoint'],
      ['run', { len: 12, foes: 2 }],
      ['arena', { boss: 'stag' }],
    ],
    signs: { 9: 'Too far to jump. One end on the far wall, one at your feet.', 11: 'A timed door: shoot the switch, then run.' },
  },
  {
    id: 3,
    key: 'farm',
    lamp: '#cfe6ff',
    wallDecor: [{ kind: 'rackface', color: '#4fb8ff' }, { kind: 'rackface', color: '#4fb8ff' }, { kind: 'pipes', color: '#5a6678', color2: '#4fb8ff', depth: 0.6 }],
    title: 'Render Farm',
    boss: 'scheduler',
    humanity: 0.22,
    seed: 303,
    width: 8,
    roof: 9,
    accent: '#4fb8ff',
    tier: 'early',
    trench: { depth: 5, kind: 'electric', color: '#4fb8ff' },
    brief: 'The grid is not a place. It is heat, in a hall of machines somewhere, being computed. This is the hall.',
    record: 'LOG: The program has found the hardware. It is walking between the racks that draw its own world, and it is not stopping.',
    roster: [
      { move: 'zigzag', look: 'drone', color: '#4fb8ff' },
      { move: 'walker', look: 'crawler', color: '#9dc8ff' },
      { move: 'turret', look: 'camturret', color: '#ff5c4a' },
      { move: 'trundle', look: 'sweeper', color: '#ffb347' },
    ],
    decor: [],
    sections: [
      ['start', { len: 14 }],
      ['run', { len: 16, foes: 1 }],
      ['rooftop'],
      ['laser', { n: 2 }],
      ['gap', { gap: 3 }],
      ['fans', { h: 6 }],
      ['checkpoint'],
      ['vault'],
      ['turn', { dir: 1 }],
      ['run', { len: 16, foes: 2 }],
      ['hideaway', { puzzle: 'slit', prize: 'cell' }],
      ['glitch'],
      ['lift', { h: 6 }],
      ['secret', { prize: 'strong' }],
      ['checkpoint'],
      ['laser', { n: 3, on: 1.5 }],
      ['stones', { n: 4 }],
      ['bulkhead', { gapH: 1.15, thick: 3 }],
      ['turn', { dir: -1 }],
      ['checkpoint'],
      ['run', { len: 14, foes: 2 }],
      ['crawl', { hidden: true }],
      ['arena', { boss: 'scheduler', height: 12, roofed: true, roofPortal: true, size: 36 }],
    ],
    signs: { 5: 'A fan. Step off the edge into its draft: it carries you up to the lit ledge.', 7: 'Armoured glass: you can see through it, and open an end on what is behind it. Nothing solid gets in.' },
  },
  {
    id: 4,
    key: 'foundry',
    lamp: '#ffd8a0',
    wallDecor: [{ kind: 'furnace', depth: 0.5 }, { kind: 'pipes', color: '#6a5a4a', color2: '#b8603a', depth: 0.6 }, { kind: 'furnace', depth: 0.5 }],
    title: 'The Foundry',
    boss: 'forgewright',
    humanity: 0.35,
    seed: 404,
    width: 8,
    roof: 11,
    accent: '#ff9a4a',
    tier: 'middle',
    trench: { depth: 5, kind: 'molten', color: '#ff6a1a' },
    brief: 'Where the grid needed hands in the world, it had them made here. Yours were poured in this room.',
    record: 'LOG: The program is in the foundry. It has stopped in front of the moulds. It is looking at them for a long time.',
    roster: [
      { move: 'walker', look: 'welder', color: '#ff9a4a' },
      { move: 'turret', look: 'arm', color: '#ffd23f' },
      { move: 'trundle', look: 'forklift', color: '#ffb347' },
      { move: 'hopper', look: 'sparkbot', color: '#ff6a1a' },
      { move: 'lancer', look: 'guard', color: '#c8c8d0' },
    ],
    decor: [],
    sections: [
      ['start', { len: 14 }],
      ['run', { len: 16, foes: 1 }],
      ['lookback', { hidden: true }],
      ['crusher', { n: 2 }],
      ['gap', { gap: 5, run: true }],
      ['checkpoint'],
      ['launch', { gap: 10 }],
      ['run', { len: 14, foes: 2 }],
      ['targets'],
      ['turn', { dir: -1 }],
      ['mover', { gap: 13 }],
      ['climb', { steps: 3, rise: 1.5 }],
      ['checkpoint'],
      ['crusher', { n: 3, period: 2.8 }],
      ['switchdoor', { timed: 6 }],
      ['fans', { h: 7 }],
      ['secret', { prize: 'big' }],
      ['turn', { dir: 1 }],
      ['checkpoint'],
      ['chasm', { gap: 13, rise: 1 }],
      ['run', { len: 14, foes: 2 }],
      ['hideaway', { puzzle: 'slit', prize: 'strong', hidden: true }],
      ['rooftop', { hidden: true }],
      ['stones', { n: 4, hard: true }],
      ['checkpoint'],
      ['run', { len: 10, foes: 1 }],
      ['arena', { boss: 'forgewright', height: 14, size: 40 }],
    ],
    signs: { 6: 'Too far to jump, and the shimmer over the gap takes no end. Go round the ramp to the edge and look back: one end on its face, one at your feet, and it throws you across.', 7: 'That one carries a shield. Come at it from the side.', 15: 'A fan. Step off the edge into its draft: it carries you up to the lit ledge.' },
  },
  {
    id: 5,
    key: 'freeway',
    rails: { h: 1, w: 0.4, role: 'wall' },
    title: 'Night Freeway',
    boss: 'interceptor',
    humanity: 0.45,
    seed: 505,
    width: 10,
    accent: '#ffb35a',
    tier: 'middle',
    brief: 'The first road it has ever seen, forty metres up on its pillars, and every lamp on it the colour of old honey.',
    record: 'OBSERVATION: The unit is on the elevated freeway, heading inland. It is moving with the traffic, not against it.',
    roster: [
      { move: 'gunner', look: 'patrol', color: '#ff5c4a' },
      { move: 'turret', look: 'trafficcam', color: '#ffb35a' },
      { move: 'chaser', look: 'bike', color: '#c8c8d0' },
      { move: 'zigzag', look: 'drone', color: '#ffb35a' },
      { move: 'lancer', look: 'guard', color: '#8a9ab8' },
    ],
    decor: [{ kind: 'lamp', color: '#ffb35a', off: -0.8, spread: 0 }, { kind: 'lamp', color: '#ffb35a', off: -0.8, spread: 0 }, { kind: 'car', color: '#b8322a', off: 4, spread: 30, dy: -38 }],
    far: [{ kind: 'building', color: '#2a3040', color2: '#ffd98a', n: 40, h: 60 }],
    ground: { y: -40, mat: 'asphalt', color: '#1a1c22' },
    sections: [
      ['start', { len: 16 }],
      ['run', { len: 20, foes: 1 }],
      ['gap', { gap: 6, run: true }],
      ['springs', { h: 6 }],
      ['checkpoint'],
      ['mover', { gap: 16 }],
      ['run', { len: 18, foes: 2 }],
      ['cache', { hidden: true }],
      ['ambush', { waves: 2 }],
      ['turn', { dir: 1 }],
      ['checkpoint'],
      ['chasm', { gap: 14, rise: -2 }],
      ['gap', { gap: 6.2, run: true }],
      ['run', { len: 16, foes: 2 }],
      ['hideaway', { puzzle: 'slit', prize: 'durable', hidden: true }],
      ['rooftop'],
      ['secret', { prize: 'durable' }],
      ['launch', { gap: 10.5, rise: 1 }],
      ['checkpoint'],
      ['stones', { n: 5, hard: true }],
      ['turn', { dir: -1 }],
      ['switchdoor', { timed: 6 }],
      ['run', { len: 18, foes: 2 }],
      ['crawl', { hidden: true }],
      ['checkpoint'],
      ['springs', { h: 7 }],
      ['run', { len: 12, foes: 2 }],
      ['arena', { boss: 'interceptor', size: 44 }],
    ],
    signs: {},
  },
  {
    id: 6,
    key: 'rain',
    rails: { h: 0.8, w: 0.3, role: 'wall' },
    title: 'Rain City',
    boss: 'broadcaster',
    humanity: 0.55,
    seed: 606,
    width: 9,
    accent: '#ff4fd8',
    tier: 'middle',
    brief: 'Rooftops in the rain. The last neon anyone still bothers to light, and in the wet between the signs, places where the grid is leaking through.',
    record: 'OBSERVATION: The unit crossed the river at 02:14. It stopped under a sign that was flickering and waited until the sign came on.',
    roster: [
      { move: 'chaser', look: 'dog', color: '#c8c8d0' },
      { move: 'gunner', look: 'secdrone', color: '#ff5c4a' },
      { move: 'turret', look: 'searchlight', color: '#fff0c8' },
      { move: 'zigzag', look: 'glyph', color: '#ff4fd8', folded: true },
      { move: 'lancer', look: 'guard', color: '#8a9ab8' },
    ],
    decor: [{ kind: 'sign', color: '#ff4fd8', off: 1, spread: 2, dy: 3 }, { kind: 'sign', color: '#4fe0ff', off: 1, spread: 2, dy: 4 }],
    far: [{ kind: 'building', color: '#3a3a44', color2: '#ffd98a', n: 50, h: 45, mat: 'brick' }],
    ground: { y: -30, mat: 'asphalt', color: '#16181e' },
    sections: [
      ['start', { len: 14 }],
      ['run', { len: 16, foes: 1 }],
      ['rooftop'],
      ['blink', { n: 4 }],
      ['gap', { gap: 5.5, run: true }],
      ['checkpoint'],
      ['wellpit', { gap: 9 }],
      ['run', { len: 16, foes: 2 }],
      ['lookback', { hidden: true }],
      ['turn', { dir: -1 }],
      ['orbit'],
      ['climb', { steps: 3 }],
      ['checkpoint'],
      ['blink', { n: 6 }],
      ['secret', { prize: 'freeze' }],
      ['chasm', { gap: 13, rise: 2 }],
      ['turn', { dir: 1 }],
      ['checkpoint'],
      ['run', { len: 16, foes: 3 }],
      ['hideaway', { puzzle: 'ledge', prize: 'cell', hidden: true }],
      ['targets'],
      ['wellpit', { gap: 10, pull: 380 }],
      ['stones', { n: 5, hard: true }],
      ['vault'],
      ['checkpoint'],
      ['run', { len: 12, foes: 2 }],
      ['arena', { boss: 'broadcaster', size: 40 }],
    ],
    signs: { 6: 'The grid is leaking through here: a black hole under the gap. Every jump over it bends.', 10: 'A switch in a pocket nothing straight can reach. Fire up past the black hole.' },
  },
  {
    id: 7,
    key: 'underline',
    lamp: '#fff0d0',
    wallDecor: [{ kind: 'poster', color: '#c83a2a' }, { kind: 'poster', color: '#2a6ac8' }, { kind: 'poster', color: '#e8b83a' }, { kind: 'tileband', color: '#3a6a4a', depth: 0.05 }],
    title: 'Underline',
    boss: 'borer',
    humanity: 0.66,
    seed: 707,
    width: 8,
    roof: 7,
    accent: '#ffd08a',
    tier: 'late',
    trench: { depth: 3, kind: 'electric', color: '#ffd08a' },
    brief: 'Under the city, the trains still run on a timetable nobody reads. The tiles were laid by hand, a hundred years ago.',
    record: 'OBSERVATION: The unit is in the old tunnels. A night worker saw it and it raised a hand. She says it waved.',
    roster: [
      { move: 'trundle', look: 'sweeper', color: '#c8a050' },
      { move: 'walker', look: 'rat', color: '#8a8478' },
      { move: 'turret', look: 'camturret', color: '#ff5c4a' },
      { move: 'hopper', look: 'dog', color: '#c8c8d0' },
      { move: 'lancer', look: 'guard', color: '#8a9ab8' },
      { move: 'zigzag', look: 'spark', color: '#7fe9ff', folded: true },
    ],
    decor: [],
    sections: [
      ['start', { len: 14 }],
      ['run', { len: 18, foes: 2 }],
      ['cache', { hidden: true }],
      ['crusher', { n: 2, period: 3 }],
      ['gap', { gap: 5, run: true }],
      ['checkpoint'],
      ['ambush', { waves: 2 }],
      ['bulkhead', { gapH: 1.1, thick: 3.5 }],
      ['turn', { dir: 1 }],
      ['laser', { n: 3 }],
      ['checkpoint'],
      ['mover', { gap: 15 }],
      ['run', { len: 16, foes: 2 }],
      ['hideaway', { puzzle: 'ledge', prize: 'freeze', hidden: true }],
      ['crawl', { hidden: true }],
      ['secret', { prize: 'big' }],
      ['lift', { h: 5 }],
      ['turn', { dir: -1 }],
      ['checkpoint'],
      ['crusher', { n: 3, period: 2.8 }],
      ['stones', { n: 5, hard: true }],
      ['switchdoor', { timed: 5 }],
      ['ambush', { waves: 3 }],
      ['checkpoint'],
      ['vault'],
      ['run', { len: 16, foes: 3 }],
      ['rooftop', { hidden: true }],
      ['drop', { h: 3 }],
      ['checkpoint'],
      ['run', { len: 12, foes: 2 }],
      ['arena', { boss: 'borer', height: 10, size: 40 }],
    ],
    signs: {},
  },
  {
    id: 8,
    key: 'harbour',
    title: 'Harbour at Dawn',
    boss: 'gantry',
    humanity: 0.78,
    seed: 808,
    width: 9,
    accent: '#ffd0a0',
    tier: 'late',
    trench: null,
    brief: 'The sun comes up over the water, and the first thing it lights is the cranes. Everything here is going somewhere someone else decided.',
    record: 'NOTE (handwritten): It got past the quay cameras. It stopped to watch the sun come up. Why would it do that?',
    roster: [
      { move: 'gunner', look: 'quad', color: '#e8e8e8' },
      { move: 'walker', look: 'crab', color: '#d8a030' },
      { move: 'circler', look: 'buoy', color: '#ff5c4a' },
      { move: 'diver', look: 'gull', color: '#f0f0f0' },
      { move: 'lancer', look: 'guard', color: '#8a9ab8' },
    ],
    decor: [{ kind: 'buoy', color: '#d83a2a', color2: '#ffe066', off: 6, spread: 20, dy: -8 }],
    far: [{ kind: 'crane', color: '#d8a030', n: 6 }],
    ground: { y: -8, mat: 'water', color: '#1e4a6a', water: true },
    sections: [
      ['start', { len: 14 }],
      ['run', { len: 16, foes: 1 }],
      ['lookback', { hidden: true }],
      ['gap', { gap: 5.5, run: true }],
      ['mover', { gap: 16 }],
      ['checkpoint'],
      ['chasm', { gap: 14 }],
      ['climb', { steps: 3, rise: 1.6 }],
      ['turn', { dir: 1 }],
      ['launch', { gap: 10, rise: 1 }],
      ['run', { len: 16, foes: 2 }],
      ['rooftop'],
      ['checkpoint'],
      ['lift', { h: 7 }],
      ['stones', { n: 5, hard: true }],
      ['secret', { prize: 'triple' }],
      ['ambush', { waves: 2 }],
      ['turn', { dir: -1 }],
      ['checkpoint'],
      ['vault'],
      ['mover', { gap: 18 }],
      ['run', { len: 16, foes: 3 }],
      ['hideaway', { puzzle: 'ledge', prize: 'big', hidden: true }],
      ['targets'],
      ['checkpoint'],
      ['bulkhead', { gapH: 1.2, thick: 3 }],
      ['gap', { gap: 6, run: true, rise: -1 }],
      ['run', { len: 12, foes: 2 }],
      ['arena', { boss: 'gantry', size: 40, height: 16 }],
    ],
    signs: {},
  },
  {
    id: 9,
    key: 'ridge',
    title: 'Pine Ridge',
    boss: 'lookout',
    humanity: 0.9,
    seed: 909,
    width: 8,
    accent: '#dff6ff',
    tier: 'late',
    brief: 'The road to the house runs up through the pines. Snow on everything. Somewhere above, a dish is turning to look.',
    record: 'NOTE (handwritten): It is coming up the mountain. I told the Lookout to stop it. I did not tell it why.',
    roster: [
      { move: 'diver', look: 'hawk', color: '#c8b8a0' },
      { move: 'chaser', look: 'hunter', color: '#a88a6a' },
      { move: 'turret', look: 'sentry', color: '#dff6ff' },
      { move: 'gunner', look: 'quad', color: '#e8e8e8' },
      { move: 'zigzag', look: 'glyph', color: '#7fe9ff', folded: true },
      { move: 'lancer', look: 'guard', color: '#8a9ab8' },
    ],
    decor: [{ kind: 'pine', color: '#2f5a33', snow: true, off: 1, spread: 16 }, { kind: 'pine', color: '#3a6a3a', snow: true, off: 4, spread: 22 }, { kind: 'rock', color: '#8a8a88', off: 1, spread: 8 }],
    far: [{ kind: 'mountain', color: '#8a8f99', snow: true, n: 14 }],
    ground: { y: -30, mat: 'snow', color: '#e8eef4' },
    sections: [
      ['start', { len: 14 }],
      ['run', { len: 18, foes: 2 }],
      ['targets'],
      ['springs', { h: 6 }],
      ['stones', { n: 5, hard: true }],
      ['checkpoint'],
      ['wellpit', { gap: 10, pull: 400 }],
      ['tower', { h: 14 }],
      ['turn', { dir: 1 }],
      ['chasm', { gap: 14, rise: -2 }],
      ['checkpoint'],
      ['blink', { n: 6 }],
      ['run', { len: 18, foes: 3 }],
      ['crawl', { hidden: true }],
      ['orbit'],
      ['secret', { prize: 'shield' }],
      ['turn', { dir: -1 }],
      ['checkpoint'],
      ['launch', { gap: 10, rise: 1 }],
      ['gap', { gap: 6.2, run: true, rise: 1 }],
      ['ambush', { waves: 3 }],
      ['checkpoint'],
      ['bulkhead', { gapH: 1.1, thick: 4 }],
      ['springs', { h: 7 }],
      ['run', { len: 16, foes: 3 }],
      ['hideaway', { puzzle: 'ledge', prize: 'cell', hidden: true }],
      ['cache', { hidden: true }],
      ['turn', { dir: 1 }],
      ['checkpoint'],
      ['vault'],
      ['stones', { n: 6, hard: true }],
      ['run', { len: 12, foes: 2 }],
      ['arena', { boss: 'lookout', size: 42 }],
    ],
    signs: {},
  },
  {
    id: 10,
    key: 'workshop',
    lamp: '#ffe0b0',
    wallDecor: [{ kind: 'shelf', depth: 0.5, body: '#6b4a2e' }, { kind: 'painting', color: '#c8b890' }, { kind: 'window', color: '#ffd8a0' }, { kind: 'clock' }, { kind: 'shelf', depth: 0.5, body: '#5a3a22' }],
    title: 'The Workshop',
    boss: 'creator',
    humanity: 1,
    seed: 1010,
    width: 8,
    roof: 9,
    accent: '#ffd08a',
    tier: 'late',
    trench: { depth: 4, kind: 'spikes', color: '#b8903a' },
    brief: 'An old clock tower on the ridge, full of wood and brass and paper. The grid was drawn here first, by hand, on a desk by the window.',
    record: 'NOTE (handwritten): It is in the house. I can hear it on the stairs. It is taking them one at a time, like a person.',
    roster: [
      { move: 'walker', look: 'automaton', color: '#b8903a' },
      { move: 'hopper', look: 'tintoy', color: '#c83a2a' },
      { move: 'diver', look: 'cuckoo', color: '#8a5a36' },
      { move: 'circler', look: 'orrery', color: '#d8b050' },
      { move: 'lancer', look: 'guard', color: '#b8903a' },
      { move: 'zigzag', look: 'glyph', color: '#7fe9ff', folded: true },
    ],
    decor: [],
    sections: [
      ['start', { len: 14 }],
      ['run', { len: 16, foes: 2 }],
      ['rooftop', { hidden: true }],
      ['climb', { steps: 3 }],
      ['crusher', { n: 2, period: 3 }],
      ['checkpoint'],
      ['vault'],
      ['mover', { gap: 14 }],
      ['turn', { dir: 1 }],
      ['tower', { h: 12 }],
      ['checkpoint'],
      ['blink', { n: 5 }],
      ['orbit'],
      ['secret', { prize: 'strong' }],
      ['ambush', { waves: 3 }],
      ['turn', { dir: -1 }],
      ['checkpoint'],
      ['launch', { gap: 10 }],
      ['stones', { n: 6, hard: true }],
      ['targets'],
      ['bulkhead', { gapH: 1.15, thick: 3 }],
      ['checkpoint'],
      ['laser', { n: 3, on: 1.5 }],
      ['chasm', { gap: 14 }],
      ['run', { len: 16, foes: 3 }],
      ['hideaway', { puzzle: 'ledge', prize: 'strong', hidden: true }],
      ['lookback', { hidden: true }],
      ['turn', { dir: 1 }],
      ['checkpoint'],
      ['wellpit', { gap: 10, pull: 420 }],
      ['switchdoor', { timed: 5 }],
      ['run', { len: 12, foes: 2 }],
      ['arena', { boss: 'creator', height: 14, size: 42 }],
    ],
    signs: {},
  },
];

/**
 * Echo, the bonus level: open once every secret in the ten has been found.
 * The grid as it remembers the robot, in red: the hardest of every kind of
 * stretch the grid ever built, one after another, and at the end the Warden
 * as the grid remembers it. Not part of the campaign's run.
 */
export const ECHO = {
  id: 11,
  key: 'echo',
  bonus: true,
  title: 'Echo',
  boss: 'echo',
  humanity: 0,
  seed: 1111,
  width: 8,
  accent: '#ff3a6a',
  tier: 'bonus',
  brief: 'Every secret found. Behind the last of them, a door the grid kept a copy of, and past it the grid, as it remembers you.',
  record: 'LOG, RESTORED FROM BACKUP: The program is outside the grid. The grid has kept a copy of every room it passed through. It is keeping them for when it comes back.',
  roster: [
    { move: 'flier', look: 'glyph', color: '#ff3a6a' },
    { move: 'walker', look: 'cubelet', color: '#ffd36a' },
    { move: 'zigzag', look: 'spark', color: '#ff9a3a' },
    { move: 'turret', look: 'prism', color: '#ff5c7a' },
    { move: 'chaser', look: 'cubelet', color: '#ff9ac8' },
  ],
  decor: [{ kind: 'monolith', color: '#c2185b', off: 6, spread: 14 }, { kind: 'wiretree', color: '#ff3a6a', color2: '#ffd36a', off: 3, spread: 8 }],
  far: [{ kind: 'mountain', color: '#c2185b', n: 10 }],
  sections: [
    ['start', { len: 14 }],
    ['run', { len: 14, foes: 2 }],
    ['blink', { n: 6 }],
    ['gap', { gap: 6, run: true }],
    ['checkpoint'],
    ['chasm', { gap: 14 }],
    ['stones', { n: 6, hard: true }],
    ['orbit'],
    ['checkpoint'],
    ['ambush'],
    ['launch'],
    ['turn', { dir: 1 }],
    ['wellpit', { gap: 10, pull: 600 }],
    ['checkpoint'],
    ['vault'],
    ['springs', { h: 7 }],
    ['tower'],
    ['bulkhead'],
    ['run', { len: 12, foes: 3 }],
    ['checkpoint'],
    ['arena', { boss: 'echo', size: 40 }],
  ],
  signs: {},
};

/** The kinds of stretch that hide a secret: the level's count of them is its count of secrets. */
export const SECRET_KINDS = ['secret', 'loft', 'crawl', 'cache', 'lookback', 'glitch', 'targets', 'rooftop', 'hideaway'];

/** How many secrets a level hides, without building it: the title's list asks this of every level. */
export function secretsIn(def) {
  return def.sections.filter(([t]) => SECRET_KINDS.includes(t)).length;
}

export function levelDef(id) {
  return id === ECHO.id ? ECHO : LEVEL_DEFS.find((l) => l.id === id);
}

/** Build level `id` into a blueprint: the world, where to start, what is in it, and how it is crossed. */
export function level(id, opts = {}) {
  const def = levelDef(id);
  const b = new Builder(def);
  def.sections.forEach(([type, o], i) => {
    const own = SECRETS[type];
    const fn = SECTIONS[type] || own;
    if (!fn) throw new Error(`no section ${type}`);
    b.difficulty = i / def.sections.length;
    const before = b.route.length;
    const at = b.cur.p;
    if (own) {
      // A secret's stretch draws on its own numbers, so adding one leaves the rest of the level as it was.
      const keep = b.r;
      b.r = rng((def.seed || 1) * 31 + i);
      fn(b, o || {});
      b.r = keep;
    } else fn(b, o || {});
    const text = def.signs && def.signs[i];
    if (text) b.signs.push({ p: at, text, reach: 9 });
    b.sections[b.sections.length - 1].route = [before, b.route.length];
  });
  scenery(b, def);
  // In the Creator's house, he talks to you as you climb through it.
  if (def.key === 'workshop') {
    const run = b.sections.filter((x) => x.type !== 'arena');
    for (const l of WORKSHOP_LINES) {
      const sec = run[Math.min(run.length - 1, Math.floor(l.at * run.length))];
      const p = sec.from;
      b.lines.push({ min: [p[0] - 7, p[1] - 3, p[2] - 7], max: [p[0] + 7, p[1] + 6, p[2] + 7], who: 'human', text: l.text, name: 'The Creator' });
    }
  }
  const bp = b.finish();
  const theme = THEMES[def.key];
  bp.theme = { ...theme, roles: { ...COMMON_ROLES, ...theme.roles } };
  bp.id = id;
  bp.def = def;
  bp.title = def.title;
  bp.humanity = def.humanity;
  bp.spawn = b.spawn;
  bp.arena = b.arena;
  if (opts.noEnemies) bp.enemies = [];
  return bp;
}

/** The far scenery: mountains, towers, the ground a long way down. */
function scenery(b, def) {
  const W = b.world;
  let min = [Infinity, 0, Infinity];
  let max = [-Infinity, 0, -Infinity];
  for (const s of W.solids) {
    min = [Math.min(min[0], s.min[0]), 0, Math.min(min[2], s.min[2])];
    max = [Math.max(max[0], s.max[0]), 0, Math.max(max[2], s.max[2])];
  }
  const c = [(min[0] + max[0]) / 2, 0, (min[2] + max[2]) / 2];
  const R = Math.max(max[0] - min[0], max[2] - min[2]) / 2 + 60;
  const r = b.r;
  for (const f of def.far || []) {
    for (let i = 0; i < f.n; i++) {
      const a = (i / f.n) * Math.PI * 2 + r() * 0.4;
      const d = R + 30 + r() * 120;
      b.props.push({ ...f, p: [c[0] + Math.cos(a) * d, (def.ground ? def.ground.y : -20) - 2, c[2] + Math.sin(a) * d], yaw: r() * 6, seed: Math.floor(r() * 1e6), h: f.h ? f.h * (0.6 + r() * 0.8) : undefined });
    }
  }
  if (def.ground) {
    const g = def.ground;
    b.props.push({ kind: 'plane', p: [c[0], g.y, c[2]], w: R * 2 + 600, d: R * 2 + 600, color: g.color, mat: g.mat });
    // Water is not somewhere to land: a fall into the harbour is a fall.
    if (g.water) W.hazards.push({ min: [c[0] - R - 300, g.y - 3, c[2] - R - 300], max: [c[0] + R + 300, g.y + 0.3, c[2] + R + 300], kind: 'water' });
  }
}

export { THEMES };
